[CLOUDTRUST-2937] Editing PII must void accreditations (add missing fields)
cloudtrust/keycloak-bridge pull request #283
Opened 2021-01-27 10:32 UTC by fperot74

2021-01-28 08:29 UTC, fratt-elca requested changes
Only the DEP fields should void the accreditations :
- firstName
- lastName
- gender
- birthDate
- idDocumentNumber

PS1 : Sorry, the JIRA was not detailed enough, it's my fault.

PS2 : When we will implement the "Attribute management" and "Accreditations management" User Stories, this will be dynamic and each type of accreditations will require their own list of fields, and will be lost if one of those fields is changed. But for now, it's hardcoded for DEP because we're on production with that one.

2021-01-28 08:29 UTC, fratt-elca commented on pkg/management/component.go
> +	var userInfosUpdated = keycloakb.IsUpdated(user.BirthLocation, oldDbUser.BirthLocation,
birthLocation is not a DEP mandatory field

2021-01-28 08:29 UTC, fratt-elca commented on pkg/management/component.go
> +		user.Nationality, oldDbUser.Nationality,
nationality is not a DEP mandatory field

2021-01-28 08:29 UTC, fratt-elca commented on pkg/management/component.go
> +		user.IDDocumentType, oldDbUser.IDDocumentType,
idDocumentType is not a DEP mandatory field

2021-01-28 08:29 UTC, fratt-elca commented on pkg/management/component.go
> +		user.IDDocumentExpiration, oldDbUser.IDDocumentExpiration,
idDocumentExpiration is not a DEP mandatory field

2021-01-28 08:29 UTC, fratt-elca commented on pkg/management/component.go
> +		user.IDDocumentCountry, oldDbUser.IDDocumentCountry)
idDocumentCountry is not a DEP mandatory field

2021-01-28 08:29 UTC, fratt-elca commented on pkg/management/component.go
> +		user.IDDocumentCountry, oldDbUser.IDDocumentCountry)
idDocumentCountry is not a DEP mandatory field

2021-01-29 13:21 UTC, fratt-elca approved these changes
It works.

2021-02-05 08:08 UTC, harture approved these changes

2021-02-05 14:50 UTC, merged