[CLOUDTRUST-3208] URL management for email action
cloudtrust/keycloak-bridge pull request #320
Opened 2021-05-26 16:14 UTC by fperot74

2021-05-27 09:34 UTC, harture requested changes

2021-05-28 08:04 UTC, fperot74 commented on configs/keycloak_bridge.yml
>  keycloak-oidc-uri: http://localhost:8080 http://127.0.0.1:8080
Done

2021-05-28 08:06 UTC, fperot74 commented on cmd/keycloakb/keycloak_bridge.go
> +	var keycloakPublicURL = keycloakConfig.AddrTokenProvider[0]
There is no change here. We already was using only the first item

2021-05-28 12:57 UTC, harture commented on cmd/keycloakb/keycloak_bridge.go
> +	var keycloakPublicURL = keycloakConfig.AddrTokenProvider[0]
I think we should not use it anymore. As it always depends of the realm

2021-05-28 12:57 UTC, harture commented on cmd/keycloakb/keycloak_bridge.go
> +		route.Handle("/", commonhttp.MakeVersionHandler(keycloakb.ComponentName, ComponentID, keycloakb.Version, Environment, GitCommit))
Why we can now remove it ? is it an "error" from the beginning or a new feature from http ?

2021-05-28 15:30 UTC, harture approved these changes

2021-05-31 14:24 UTC, merged