Merge with current bridge version
cloudtrust/keycloak-bridge pull request #367
Opened 2021-12-08 10:32 UTC by basbeu

2021-12-13 19:32 UTC, harture requested changes

2021-12-13 19:32 UTC, harture commented on api/management/swagger-api_management.yaml
> +  description: 'Mangement API for Cloudtrust'
Added a typo

2021-12-13 19:32 UTC, harture commented on api/management/swagger-api_management.yaml
> +  description: 'Mangement API for Cloudtrust'
Are you sure this PR is rebase on the last version of master ?

2021-12-20 10:02 UTC, harture approved these changes

2021-12-20 10:14 UTC, basbeu commented on vendor/modules.txt
> +# github.com/cloudtrust/common-service/v2 v2.5.3-0.20211209095354-0125f4bc4c77
Yes, thank you. It was planned to be changed once I merged the PR in the common-service !

2021-12-20 10:19 UTC, basbeu commented on pkg/management/component.go
> +	err := c.authChecker.ReloadAuthorizations(ctx)
Done

2021-12-20 10:19 UTC, basbeu commented on pkg/management/component.go
> +	err := c.authChecker.ReloadAuthorizations(ctx)
Done

2021-12-20 10:33 UTC, basbeu commented on pkg/management/component.go
> +				// clean children
Done

2021-12-20 10:42 UTC, basbeu commented on pkg/management/component.go
> +	targetGroupName := &targetGroupID
Done

2021-12-20 11:22 UTC, basbeu commented on pkg/management/component.go
> +	scope, _ := getScope(authz)
done

2021-12-20 11:22 UTC, basbeu commented on pkg/management/component.go
> +			scope, _ := getScope(authz)
done

2021-12-20 11:22 UTC, basbeu commented on pkg/management/component.go
> +	targetGroupName := &targetGroupID
done

2021-12-20 11:22 UTC, basbeu commented on pkg/management/component.go
> +	} else if *targetGroupName != "*" {
done

2021-12-20 11:22 UTC, basbeu commented on pkg/management/component.go
> +	if *targetGroupName == "" {
done

2021-12-20 12:35 UTC, merged