[CLOUDTRUST-5511] Add initial onboarding status on user creation
cloudtrust/keycloak-bridge pull request #506
Opened 2024-10-16 08:03 UTC by Xelowak

2024-10-16 08:30 UTC, fperot74 approved these changes
Can't review this PR... it is polluated by lots of unexpected formatting changes

2024-10-16 08:30 UTC, fperot74 commented on internal/business/gln_test.go
> +	anError := errors.New("an error")
Has a change in formatting been agreed in the team?

2024-10-17 11:17 UTC, harture requested changes
Not against applying new formatting but it must be in a separated commit else it cannot be reviewed.
However, we have to agree altogether if we want to apply a new formatting else it will be quickly a nightmare for everyone :) Let's discuss it

2024-10-18 09:07 UTC, Xelowak commented
I close this PR and open a new one because of formatting issues

2024-10-18 09:08 UTC, closed without merging